### ISSUE TITLE
locally application failed: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by asun233** [hydrocode-de/skgstat_uncertainty#1]
as following:
 Traceback (most recent call last):
  File "d:\xxxx\mt\lib\site-packages\streamlit\script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
  File "c:\users\xxxx\skgstat_uncertainty\skgstat_uncertainty\apps\index.py", line 9, in <module>
    from ..core import Project
ImportError: attempted relative import with no known parent package

how to solve it ?

**Comment by mmaelicke** [comment]
Thanks for reporting

I'll try to solve this, but until then you can try to run the app like:
`streamlit run /path/to/streamlit_app.py`

**Comment by mmaelicke** [comment]
I think it was fixed with version `0.9.4`, offline and online.
You can upgrade like:

`pip install --upgrade skgstat_uncertainty` if you installed from PyPI or `pip install -e .` from within the repo, if you cloned the repo locally.

It would be nice to hear if it is working now.
